// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TODO.API.Data;

namespace TODO.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190217015617_itemSeeding2")]
    partial class itemSeeding2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("TODO.API.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.ToTable("TODOS");

                    b.HasData(
                        new { Id = 1, Description = "First thing to do", Time = new DateTime(2015, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { Id = 2, Description = "Second thing to do", Time = new DateTime(2018, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
